### ISSUE TITLE
fetch returns a sting instead of a table.

### ISSUE THREAD

**Issue by laigor** [lunarmodules/luasql#130]
fetch return all row data as sting.
```
local driver = require "luasql.odbc"
local odbc_env = driver.odbc()
local odbc_conn = odbc_env:connect("...","...","...")
local odbc_cur = odbc_conn:execute('select .....')
print(type(odbc_cur:fetch()))
```
return:
```
string
```

**Comment by tomasguisasola** [comment]
Hi

Check the docs (
https://keplerproject.github.io/luasql/manual.html#cursor_object):

   "If fetch is called without parameters, the results will be returned
directly to the caller. If fetch is called with a table, the results will
be copied into the table and the changed table will be returned."

The examples (https://keplerproject.github.io/luasql/examples.html) show
how to retrieve results in a table.

Regards,
Tomás

Em ter., 28 de set. de 2021 às 07:40, laigor ***@***.***>
escreveu:
