### ISSUE TITLE
LuaRocks modules: broken link to project homepage

### ISSUE THREAD

**Issue by deining** [lunarmodules/luasql#146]
Module `luasql-odbc` is available on this [page](https://luarocks.org/modules/tomasguisasola/luasql-odbc) on `luarocks.org`. This page shows a broken link to the project home page:
http://keplerproject.github.io/luasql/

Were great if this link could be corrected to
https://lunarmodules.github.io/luasql/

The same broken link is shown for `luasql-oci8`, `luasql-firebird`, ...

**Comment by tomasguisasola** [comment]
Corrected!  Thanks!
