### ISSUE TITLE
Failed cloning git repository.

### ISSUE THREAD

**Issue by cargreg** [lunarmodules/luasql#154]
Hi,
given that i'm a newbie to lua 
i  tring to install the rock throug luarocks,

luarocks install luasql-mysql
Installing https://luarocks.org/luasql-mysql-2.6.0-1.rockspec
Cloning into 'luasql'...
Error: Failed cloning git repository.

i think that is coused by url
source = {
  url = "git://github.com/keplerproject/luasql.git",
  branch = "2.6.0",
}

if i try to clone the repo git clone git://github.com/keplerproject/luasql.git
Cloning into 'luasql'...
it hang

but if i change the protocol to https
 git clone https://github.com/keplerproject/luasql.git
Cloning into 'luasql'...
remote: Enumerating objects: 2909, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 2909 (delta 47), reused 51 (delta 30), pack-reused 2815
Receiving objects: 100% (2909/2909), 800.01 KiB | 4.71 MiB/s, done.
Resolving deltas: 100% (1767/1767), done.
it works

**Comment by tomasguisasola** [comment]
I've just uploaded new rockspecs for each driver that should solve this problem.  Anyway, I think LuaRocks 3.9 automatically manages this problem.

Please check if it corrects your problem and close this issue if it does.  Or tell me what happens.

**Comment by cargreg** [comment]
problem solved
