### ISSUE TITLE
Installing luasql error 

### ISSUE THREAD

**Issue by eeerrri** [lunarmodules/luasql#159]
Hello, I have a problem with installing luasql on my Windows 11 pc. It only says it failed at compiling module.
!
![image_2024-02-15_182333964](https://github.com/lunarmodules/luasql/assets/136094906/a881aec6-fba2-465c-a70f-f0e5aa81a9d5)

**Comment by tomasguisasola** [comment]
Note that the problem is in mysqlclient.lib (which needs libssl-3-x64.dll that might be the real problem).  The other messages are derived from that file not being handled by the linker (ld.exe).

**Comment by eeerrri** [comment]
Well i installed libssl-3-x64.dll in my sistem32 folder a restarted the computer.
And its the same problem: Failed compiling module luasql/mysql.dll

I installed the file from this website: https://www.dllme.com/dll/files/libssl-3-x64.

So there's a different problem.
