### ISSUE TITLE
Does luasql.postgres support SSL

### ISSUE THREAD

**Issue by tomdaniels41** [lunarmodules/luasql#164]
Hi,

does the luasql.postgres driver support SSL? if so how do i get it working?

Thank you for your time

**Comment by tomasguisasola** [comment]
I've never tried it but I think -- by superficially looking at the docs -- that this support depends only on the compilation of both sides, client and server.  If I am correct, you can manage to compile the driver with the apropriate configuration and install the certificate files on the client and server sides and then the connection could be established over SSL.

**Comment by tomasguisasola** [comment]
By the way, if you try the approach mentioned above, feel free to write anything about it!  If there are any impossibilities, feel free to ask for correction or improvements too.

**Comment by tomdaniels41** [comment]
Hi, I have tried, certificate are working correctly as I can connect remotely using pgAdmin with ssl and both client side and server side are correct, Is there away to force ssl? and yes, i will be happy to do a wight on how to connect with ssl when we can get it working.

thank you for your time

tom
