### ISSUE TITLE
Failure with luasql-odbc on windows platform

### ISSUE THREAD

**Issue by deining** [lunarmodules/luasql#175]
As already mwntioned in #174, I'm trying to install luasql-odbc on my Windows box. Unfortunately I'm still running into troubles:

I now managed to compile the module successfully:

```
luarocks install luasql-odbc-2.6.0-3.rockspec --lua-version 5.3 --force ODBC_DIR=c:\msys64\mingw64
Cloning into 'luasql'...
remote: Enumerating objects: 3026, done.
remote: Counting objects: 100% (312/312), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 3026 (delta 202), reused 280 (delta 194), pack-reused 2714 (from 1)
Receiving objects: 100% (3026/3026), 817.57 KiB | 1.91 MiB/s, done.
Resolving deltas: 100% (1866/1866), done.

luasql-odbc 2.6.0-3 depends on lua >= 5.1 (5.3-1 provided by VM: success)
x86_64-w64-mingw32-gcc -O2 -c -o src/luasql.o -IC:\Programs\lua53/include src/luasql.c -Ic:\msys64\mingw64\include
x86_64-w64-mingw32-gcc -O2 -c -o src/ls_odbc.o -IC:\Programs\lua53/include src/ls_odbc.c -Ic:\msys64\mingw64\include
x86_64-w64-mingw32-gcc  -shared -o C:\Users\ADEINI~1\AppData\Local\Temp\luarocks_build-LuaSQL-ODBC-2.6.0-3-5257439\luasql\odbc.dll src/luasql.o src/ls_odbc.o -Lc:\msys64\mingw64\lib -lodbc32 C:\Programs\lua53\bin\lua53.dll -lm
luasql-odbc 2.6.0-3 is now installed in C:\Users\adeininger\AppData\Roaming\luarocks (license: MIT/X11)
```

This gives me file `odbc`, file size 244 kB:

```
$ file odbc.dll
odbc.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows, 20 sections
```

However, when invoking the lua interpreter and trying to load the module, an error is thrown:

```
lua
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> require("odbc")
error loading module 'odbc' from file 'c:\programs\lua53\lib\lua\5.3\odbc.dll':
        The specified procedure could not be found.

stack traceback:
        [C]: in ?
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
>
```

Any idea what's wrong here? Are there any other dll's missing?

**Comment by tomasguisasola** [comment]
LuaSQL drivers are supposed to be "required" as "luasql.<driver name>".  So you should install it in "c:\programs\lua53\lib\lua\5.3\luasql\odbc.dll" and load it with "require'luasql.odbc' ".

This relates to the way require calls the initilization function inside the dynamic library, which is a static named function.

**Comment by deining** [comment]
> LuaSQL drivers are supposed to be "required" as "luasql.". So you should install it in "c:\programs\lua53\lib\lua\5.3\luasql\odbc.dll" and load it with "require'luasql.odbc' ".
> 
> This relates to the way require calls the initilization function inside the dynamic library, which is a static named function.

Thanks for clarification! It#s working now, you saved my day!

```
lua
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> require("luasql.odbc")
table: 0000022333b79e70
>
```
